{
 "title": "Grafadruid Wikipedia Sample",
 "time": { "from": "2016-06-26T23:47:04.557Z", "to": "2016-06-27T21:28:55.611Z" },
 "templating": {
  "list": [
   {
    "name": "country",
    "query": {}
   },
   {
    "name": "city",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "SQL",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "builder": {
      "query": "SELECT \"__time\", \"channel\", \"cityName\", \"comment\", \"count\", \"countryIsoCode\", \"countryName\", \"diffUrl\", \"flags\", \"isAnonymous\", \"isMinor\", \"isNew\", \"isRobot\", \"isUnpatrolled\", \"metroCode\", \"namespace\", \"page\", \"regionIsoCode\", \"regionName\", \"sum_added\", \"sum_commentLength\", \"sum_deleted\", \"sum_delta\", \"sum_deltaBucket\", \"user\"\nFROM \"wikipedia\"\nWHERE \"cityName\" = '${city}'\nAND __time >= MILLIS_TO_TIMESTAMP(${__from}) AND __time <= MILLIS_TO_TIMESTAMP(${__to})",
      "queryType": "sql"
     },
     "settings": {
      "contextParameters": [
       { "name": "plop", "value": "plip" }
      ],
      "format": "long"
     }
    }
   ]
  },
  {
   "title": "TIMESERIES",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "builder": {
      "aggregations": [
       { "name": "count", "type": "count" },
       { "fieldName": "sum_added", "name": "delta", "type": "longLast" }
      ],
      "dataSource": { "name": "wikipedia", "type": "table" },
      "descending": false,
      "filter": {
       "dimension": "countryName",
       "extractionFn": null,
       "type": "selector",
       "value": "France"
      },
      "granularity": "minute",
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "limit": 0,
      "postAggregations": [],
      "queryType": "timeseries",
      "virtualColumns": []
     },
     "expr": "{\"builder\":{\"queryType\":\"timeseries\",\"dataSource\":{\"name\":\"wikipedia\",\"type\":\"table\"},\"descending\":false,\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]},\"granularity\":\"minute\",\"filter\":{\"dimension\":\"countryName\",\"extractionFn\":null,\"type\":\"selector\",\"value\":\"France\"},\"aggregations\":[{\"name\":\"count\",\"type\":\"count\"},{\"fieldName\":\"sum_added\",\"name\":\"delta\",\"type\":\"longLast\"}],\"postAggregations\":[],\"limit\":0,\"virtualColumns\":[]},\"settings\":{\"contextParameters\":[{\"name\":\"plop\",\"value\":\"plep\"}],\"format\":\"wide\"}}",
     "settings": {
      "contextParameters": [
       { "name": "plop", "value": "plep" }
      ],
      "format": "wide"
     }
    }
   ]
  },
  {
   "title": "TOPN",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "builder": {
      "aggregations": [
       { "fieldName": "sum_delta", "name": "delta", "type": "longSum" }
      ],
      "dataSource": { "name": "wikipedia", "type": "table" },
      "dimension": { "dimension": "regionName", "outputName": "region", "outputType": "STRING", "type": "default" },
      "filter": {
       "dimension": "countryName",
       "extractionFn": null,
       "type": "selector",
       "value": "France"
      },
      "granularity": "all",
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "metric": { "metric": "delta", "type": "numeric" },
      "postAggregations": [],
      "queryType": "topN",
      "threshold": 50,
      "virtualColumns": []
     },
     "expr": "{\"builder\":{\"queryType\":\"topN\",\"dataSource\":{\"name\":\"wikipedia\",\"type\":\"table\"},\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]},\"granularity\":\"all\",\"filter\":{\"dimension\":\"countryName\",\"extractionFn\":null,\"type\":\"selector\",\"value\":\"France\"},\"aggregations\":[{\"fieldName\":\"sum_delta\",\"name\":\"delta\",\"type\":\"longSum\"}],\"postAggregations\":[],\"dimension\":{\"dimension\":\"regionName\",\"outputName\":\"region\",\"outputType\":\"STRING\",\"type\":\"default\"},\"threshold\":50,\"metric\":{\"metric\":\"delta\",\"type\":\"numeric\"},\"virtualColumns\":[]},\"settings\":{\"contextParameters\":[{\"name\":\"plop\",\"value\":\"plep\"}],\"format\":\"wide\"}}",
     "settings": {
      "contextParameters": [
       { "name": "plop", "value": "plep" }
      ],
      "format": "wide"
     }
    }
   ]
  },
  {
   "title": "GROUPBY",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "builder": {
      "aggregations": [
       { "fieldName": "sum_delta", "name": "delta", "type": "longSum" }
      ],
      "dataSource": { "name": "wikipedia", "type": "table" },
      "dimensions": [
       { "dimension": "countryName", "outputName": "country", "outputType": "STRING", "type": "default" },
       { "dimension": "regionName", "outputName": "region", "outputType": "STRING", "type": "default" }
      ],
      "filter": {
       "dimension": "countryName",
       "extractionFn": null,
       "type": "selector",
       "value": "France"
      },
      "granularity": "minute",
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "postAggregations": [],
      "queryType": "groupBy",
      "virtualColumns": []
     },
     "expr": "{\"builder\":{\"queryType\":\"groupBy\",\"dataSource\":{\"name\":\"wikipedia\",\"type\":\"table\"},\"dimensions\":[{\"dimension\":\"countryName\",\"outputName\":\"country\",\"outputType\":\"STRING\",\"type\":\"default\"},{\"dimension\":\"regionName\",\"outputName\":\"region\",\"outputType\":\"STRING\",\"type\":\"default\"}],\"granularity\":\"minute\",\"filter\":{\"dimension\":\"countryName\",\"extractionFn\":null,\"type\":\"selector\",\"value\":\"France\"},\"aggregations\":[{\"fieldName\":\"sum_delta\",\"name\":\"delta\",\"type\":\"longSum\"}],\"postAggregations\":[],\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]},\"virtualColumns\":[]},\"settings\":{\"contextParameters\":[],\"format\":\"wide\"}}",
     "settings": {
      "contextParameters": [],
      "format": "wide"
     }
    }
   ]
  },
  {
   "title": "SCAN",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "builder": {
      "batchSize": 20480,
      "columns": [
       "__time",
       "channel",
       "cityName",
       "comment",
       "count",
       "countryIsoCode",
       "diffUrl",
       "flags",
       "isAnonymous",
       "isMinor",
       "isNew",
       "isRobot",
       "isUnpatrolled",
       "metroCode",
       "namespace",
       "page",
       "regionIsoCode",
       "regionName",
       "sum_added",
       "sum_commentLength",
       "sum_deleted",
       "sum_delta",
       "sum_deltaBucket",
       "user"
      ],
      "dataSource": { "name": "wikipedia", "type": "table" },
      "filter": {
       "dimension": "countryName",
       "extractionFn": null,
       "type": "selector",
       "value": "France"
      },
      "intervals": { "intervals": [ "${__from:date:iso}/P5D" ], "type": "intervals" },
      "limit": 0,
      "order": "none",
      "queryType": "scan",
      "virtualColumns": []
     },
     "expr": "{\"builder\":{\"queryType\":\"scan\",\"dataSource\":{\"name\":\"wikipedia\",\"type\":\"table\"},\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/P5D\"]},\"filter\":{\"dimension\":\"countryName\",\"extractionFn\":null,\"type\":\"selector\",\"value\":\"France\"},\"columns\":[\"__time\",\"channel\",\"cityName\",\"comment\",\"count\",\"countryIsoCode\",\"diffUrl\",\"flags\",\"isAnonymous\",\"isMinor\",\"isNew\",\"isRobot\",\"isUnpatrolled\",\"metroCode\",\"namespace\",\"page\",\"regionIsoCode\",\"regionName\",\"sum_added\",\"sum_commentLength\",\"sum_deleted\",\"sum_delta\",\"sum_deltaBucket\",\"user\"],\"batchSize\":20480,\"limit\":0,\"order\":\"none\",\"virtualColumns\":[]},\"settings\":{\"contextParameters\":[{\"name\":\"plop\",\"value\":\"plep\"}],\"format\":\"wide\"}}",
     "settings": {
      "contextParameters": [
       { "name": "plop", "value": "plep" }
      ],
      "format": "wide"
     }
    }
   ]
  },
  {
   "title": "SEARCH",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "builder": {
      "dataSource": { "name": "wikipedia", "type": "table" },
      "filter": {
       "dimension": "countryName",
       "extractionFn": null,
       "type": "selector",
       "value": "France"
      },
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "limit": 0,
      "query": { "type": "contains", "value": "ari" },
      "queryType": "search",
      "searchDimensions": [
       { "dimension": "regionName", "outputName": "regionName", "outputType": "STRING", "type": "default" }
      ]
     },
     "expr": "{\"builder\":{\"queryType\":\"search\",\"dataSource\":{\"name\":\"wikipedia\",\"type\":\"table\"},\"filter\":{\"dimension\":\"countryName\",\"extractionFn\":null,\"type\":\"selector\",\"value\":\"France\"},\"limit\":0,\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]},\"searchDimensions\":[{\"dimension\":\"regionName\",\"outputName\":\"regionName\",\"outputType\":\"STRING\",\"type\":\"default\"}],\"query\":{\"type\":\"contains\",\"value\":\"ari\"}},\"settings\":{\"contextParameters\":[{\"name\":\"plop\",\"value\":\"plep\"}],\"format\":\"long\"}}",
     "settings": {
      "contextParameters": [
       { "name": "plop", "value": "plep" }
      ],
      "format": "long"
     }
    }
   ]
  },
  {
   "title": "TIME BOUNDARY",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "builder": {
      "bound": null,
      "dataSource": { "name": "wikipedia", "type": "table" },
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "queryType": "timeBoundary"
     },
     "expr": "{\"builder\":{\"queryType\":\"timeBoundary\",\"dataSource\":{\"name\":\"wikipedia\",\"type\":\"table\"},\"bound\":null,\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{\"contextParameters\":[{\"name\":\"\",\"value\":\"\"}],\"format\":\"wide\"}}",
     "settings": {
      "contextParameters": [
       { "name": "", "value": "" }
      ],
      "format": "wide"
     }
    }
   ]
  },
  {
   "title": "DATASOURCE METADATA",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "builder": { "dataSource": { "name": "wikipedia", "type": "table" }, "queryType": "dataSourceMetadata" },
     "settings": {
      "contextParameters": [
       { "name": "", "value": "" }
      ],
      "format": "wide"
     }
    }
   ]
  },
  {
   "title": "SEGMENT METADATA",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "builder": {
      "analysisTypes": [
       "cardinality",
       "size",
       "aggregators",
       "interval",
       "minmax",
       "queryGranularity",
       "timestampSpec",
       "rollup"
      ],
      "dataSource": { "name": "wikipedia", "type": "table" },
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "lenientAggregatorMerge": false,
      "queryType": "segmentMetadata",
      "toInclude": { "type": "all" },
      "usingDefaultInterval": false
     },
     "expr": "{\"builder\":{\"queryType\":\"segmentMetadata\",\"dataSource\":{\"name\":\"wikipedia\",\"type\":\"table\"},\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]},\"toInclude\":{\"type\":\"all\"},\"analysisTypes\":[\"cardinality\",\"size\",\"aggregators\",\"interval\",\"minmax\",\"queryGranularity\",\"timestampSpec\",\"rollup\"],\"lenientAggregatorMerge\":false,\"usingDefaultInterval\":false},\"settings\":{\"contextParameters\":[{\"name\":\"\",\"value\":\"\"}],\"format\":\"long\",\"view\":\"columns\"}}",
     "settings": {
      "contextParameters": [
       { "name": "", "value": "" }
      ],
      "format": "long",
      "view": "columns"
     }
    }
   ]
  }
 ]
}